#!C:\Users\SONY\AppData\Local\Programs\Python\Python38\python.exe
print ("Content-type:text/html\r\n\r\n")
print ('<html>')
print ('<head>')
print ('<title>Hello World </title>')
print ('</head>')
print ('<body  bgcolor="yellow">')
print ('<h2><font color="pink"><marquee>Swami Dharisanam</marquee></font></h2>')
print('<img src="a1.jpg" height=150 width=150></img>')
print('<img src="a2.jpg" height=150 width=150></img>')
print('<img src="a3.jpg" height=150 width=150></img>')
print('<img src="a4.jpg" height=150 width=150></img>')
print ('<h1><font color="red">Amman Thunai</font></h1>')
print('<ul type="square"><li>Kamachi amman<li>Meenakshi amman<li>Parvatha valli<li>Bannari amman</ul>')
print ('<h1><font color="green" >Play the video</font></h1>')
print('<video width="320" height="240" controls> <source src="god.mp4" type="video/mp4"></video>')
print('<br>')
print ('<h1><font color="blue">Play the song Om...</font></h1>')
print('<audio  controls> SONG <source src="om.mp3" type="audio/mpeg"></audio>')
print('<br>')
print ('</body>')
print ('</html>')